import CustomNavbar from './components/shared/navbar'
import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin']})

export const metadata = {
  title: 'Shakawina',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <CustomNavbar />
        {children}
      </body>
    </html>
  )
}
